### ISSUE TITLE
Stoermelder packone

### ISSUE THREAD

**Issue by vernaillen** [flyingLowSounds/VCV-Rack-v2-Testing-Plugins#2]
I was able to build Stoermelder's packone module (from https://github.com/stoermelder/vcvrack-packone/tree/v2-dev)
against VCV Rack Community Edition 2.git.5c47e6e0

[Stoermelder-P1-2.0.0-mac.vcvplugin.zip](https://github.com/flyingLowSounds/VCV-Rack-v2-Testing-Plugins/files/7269281/Stoermelder-P1-2.0.0-mac.vcvplugin.zip)

**Comment by flyingLowSounds** [comment]
Thanks. I will try to build against the latest public beta to keep all the files consistent.
