### ISSUE TITLE
Mac builds for the new V2 beta 042a9ce0

### ISSUE THREAD

**Issue by Torinbob** [flyingLowSounds/VCV-Rack-v2-Testing-Plugins#3]
Here with some new Mac plugin builds for 042a9ce0 to add to your repo

[Mac Builds for Flying Low 042a9ce0.zip](https://github.com/flyingLowSounds/VCV-Rack-v2-Testing-Plugins/files/7271584/Mac.Builds.for.Flying.Low.042a9ce0.zip)

**Comment by flyingLowSounds** [comment]
Great!
